image: python:latest
stages:
    - test
    - docker

cache:
  paths:
    - .cache/pip
    - .cache/pypoetry

before_script:
  - pip install poetry
  - poetry install

test:
  stage: test
  script:
    - poetry run coverage run -m pytest
    - poetry run coverage report -m

docker-build-master:
  image: docker:stable
  stage: docker
  dependencies: 
    - test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  image: docker:stable
  stage: docker
  dependencies: 
    - test
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

