openapi: 3.0.0
info:
  title: applications_container API
  version: '1.0'
  description: applications_container API
  contact:
    name: Sleuth AI
    email: contact@sleuth-ai.com
    url: http://sleuth-ai.com
  termsOfService: http://sleuth-ai.com/privacy_policy
servers:
  - url: 'http://platform.sleuth-ai.com/applications_container'
paths:
  /get_ticker/{comment}:
    get:
      summary: put comment and return tickers
      tags: []
      description: put comment and return tickers
      parameters:
        - in: path
          name: comment
          schema:
            type: string
          required: true
          description: comment to find tickers in
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/tickers'
        '501':
          description: ERROR
          headers: {}
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    tickers:
      type: array
      items: 
        type: string
tags:
  - name: ticker
