openapi: 3.0.0
info:
  title: applications_container API
  version: '1.0'
  description: applications_container API
  contact:
    name: Sleuth AI
    email: contact@sleuth-ai.com
    url: http://sleuth-ai.com
  termsOfService: http://sleuth-ai.com/privacy_policy
servers:
  - url: 'http://platform.sleuth-ai.com/applications_container'
paths:
  /hello_world:
    get:
      summary: get hello world request
      tags:
        - hello-world-tag
      responses:
        '200':
          description: OK
      description: examples get request
    put:
      summary: put hello world request
      tags: []
      description: example put request
      parameters:
        - schema:
            type: string
          in: query
          name: hello_message
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  hello-world-response:
                    type: string
              examples:
                example-1:
                  value:
                    hello-world-response: some response txt
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: api.oauth.decode_token
  schemas: {}
security:
  - jwt: ['secret']
tags:
  - name: hello-world-tag
